### ISSUE TITLE
Windows curses update / Mac issue

### ISSUE THREAD

**Issue by Yoon0117** [thejoabo/autofishbot#121]
There was an error with 2.3.1, and changing the .txt to 2.3.2 fixed the issue. (On my laptop)

This keeps showing up on my mac, I'm not sure what I'm doing wrong. I used the same config file from the PC that worked fine. (Mac)
<img width="227" alt="Screenshot 2023-12-01 at 7 26 40" src="https://github.com/thejoabo/autofishbot/assets/90393596/8eb328db-ebd4-4f3c-829d-020187e87423">

**Comment by thejoabo** [comment]
This is internal error while connecting you to the Discord Gateway API, probably they rejected your IP or some other configuration. It will fix itself, try a VPN or proxy.
