### ISSUE TITLE
Issue Using The Bot

### ISSUE THREAD

**Issue by YourLazy** [thejoabo/autofishbot#124]
![wa4lh645](https://github.com/thejoabo/autofishbot/assets/154760429/224c8919-6784-4c30-af29-6f6c6fc48f7a)

**Comment by thejoabo** [comment]
Hello @YourLazy , consider adjusting the cooldown value in your config file to fall within the range of 2 to 3.5. The current value of 3.6 exceeds the specified boundaries.
