### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Jambo199** [thejoabo/autofishbot#135]
![image](https://github.com/thejoabo/autofishbot/assets/109238072/eb5e2270-c1a6-4c8a-b83a-611ec67c5cd8)
bro what

**Comment by thejoabo** [comment]
Hello @Jambo199, please double check your token value (probably is incorrect), #93 , #61

**Comment by Jambo199** [comment]
Alright, will do thx
