### ISSUE TITLE
Functionality Breakdown

### ISSUE THREAD

**Issue by wacns** [thejoabo/autofishbot#136]
Hello @thejoabo .It seems that there is such an update to either discord's api or Virtual Fisher gameplay.
Because now if you're going to run the bot it keep sending notifications that "Unknown command help", "Unknown command fish", "Unknown command buy".
The "Fish" command becomes known once i manualy type /fish or press the Fish Again button and then it fishes as normal. As well as there is an update to the gameplay of the bot as it can be seen in the next picture.
![image](https://github.com/thejoabo/autofishbot/assets/43343208/b77ff5c2-173e-401d-af2e-741e04956346)
And it fails to solve capatchas as the /verify command is Unknown as what I've mentioned above.

**Comment by thejoabo** [comment]
Hello @wacns , Discord changed their API yesterday, they've made minor adjustments to their application commands index endpoint, that's what caused the bot to misbehave. I'll try to hot-fix it today or tomorrow.
