### ISSUE TITLE
Border overlaps bait name in compact mode

### ISSUE THREAD

**Issue by notvirtio** [thejoabo/autofishbot#50]
![изображение](https://user-images.githubusercontent.com/78849100/199093655-a6dcf702-059a-4d60-9dda-0cc446130958.png)
just move this thing like 3 characters to the right

**Comment by thejoabo** [comment]
@notvirtio Thanks for reporting, it will be fixed on the next release !

**Comment by thejoabo** [comment]
Fixed in version experimental-2.0.0 ([changelog](https://github.com/thejoabo/autofishbot/blob/main/assets/changelog.md)).
