### ISSUE TITLE
Program not running

### ISSUE THREAD

**Issue by UncagedTiger** [thejoabo/autofishbot#53]
I went on git bash, and entered in all the mentioned code. It then asked me for a configuration name, and I wasn't sure what to write so I just put "start", then nothing happened. I tried running the code again, but nothing worked. Do you know anything I might have forgotten?

**Comment by thejoabo** [comment]
@UncagedTiger did you changed the values in your created config file ? The file should be at  "_./configs/{config_name}.config_" (under the virtualfisher-bot folder). If you need help to set everything up, check [FAQ](https://github.com/thejoabo/virtualfisher-bot/blob/main/assets/faq.md) and [config template](https://github.com/thejoabo/virtualfisher-bot/blob/main/assets/template.config).
