### ISSUE TITLE
Autobuy

### ISSUE THREAD

**Issue by DomeSs97** [thejoabo/autofishbot#55]
Hi, bait autobuy not working.

**Comment by thejoabo** [comment]
Hello @DomeSs97, have you filled the "BAIT" parameter and defined the "AUTO_BUY_BAITS" to true ? If so, the Scheduler controls the pace at which the commands will be sent, for bait purchase:

- the initial delay for sending the first purchase request ranges from 5 to 20 minutes.
- subsequent purchase requests (for baits) ranges from 15 to 30 minutes (+240/-120 seconds variation) .
- the amount is calculated taking into account these timings

More info at: [config guide](https://github.com/thejoabo/autofishbot/blob/main/assets/faq.md).
