### ISSUE TITLE
Random error when trying to launch

### ISSUE THREAD

**Issue by ChickenJL** [thejoabo/autofishbot#58]
This shows up when I try to launch it. I have updated pythong and installed via git.

https://i.imgur.com/P1bspzF.png

**Comment by DomeSs97** [comment]
Hi, do you have srtuped config? 

Start bot like this "Python3 autofishbot.py nameofyourconfig"

**Comment by ChickenJL** [comment]
> 

same error

**Comment by thejoabo** [comment]
Python 3.10.6 (or above required), you are using 3.8.
