### ISSUE TITLE
'NoneType'

### ISSUE THREAD

**Issue by acataeshtete** [thejoabo/autofishbot#70]
![image](https://user-images.githubusercontent.com/93230298/210217485-f51cb7f4-c0df-4f1b-a1e7-ae5b82955787.png)

How to solve this?

**Comment by thejoabo** [comment]
Hello @acataeshtete , probably invalid 'USER_TOKEN' parameter, it tries to authorize you to the webgate and fails, returning a None response (which crashes the bot).
