### ISSUE TITLE
I need help setting this up

### ISSUE THREAD

**Issue by AAnthoynyy** [thejoabo/autofishbot#71]
I have no clue how to set this up, is there a youtube I could follow or someone that could help me figure this out. thanks

**Comment by thejoabo** [comment]
Hello @AAnthoynyy, you can read these topics to help you out:
- [Default windows installation](https://github.com/thejoabo/autofishbot/discussions/65)
- [Android installation](https://github.com/thejoabo/autofishbot/discussions/68)
- [Config files guide (important)](https://github.com/thejoabo/autofishbot/blob/main/assets/faq.md)
