### ISSUE TITLE
cooldown randomizer

### ISSUE THREAD

**Issue by rominmusa** [thejoabo/autofishbot#80]
Please add an option to customize the "randomizer" for fishing cool down.

For some reason the bot is banning everyone who have miniature cool down . so i want to add cool down up-to 2 second so the cmd work with cool down b/w 3-5 which is more human like.

**Comment by thejoabo** [comment]
Hello @rominmusa, you can already change the base cooldown in your config file. The actual randomizer (which takes in consideration the base cd) follows an equation to avoid ban detection ([see here](https://github.com/thejoabo/autofishbot/discussions/12)).
