### ISSUE TITLE
Not auto fishing

### ISSUE THREAD

**Issue by MajorLOL** [thejoabo/autofishbot#83]
Greetings, 

I filled all the required fiels, and when i boot python autofishbot.py 

It show the following:
![image](https://user-images.githubusercontent.com/56225967/217349130-60c45ba5-35b0-497f-a549-8f046361fd92.png)

In short it does nothing.

Here is my debug log:
[debug.log](https://github.com/thejoabo/autofishbot/files/10678879/debug.log)

Here are my settings in my file:
![image](https://user-images.githubusercontent.com/56225967/217350038-67a85025-e0c6-44df-a274-ff8d242c61fd.png)

**Comment by MajorLOL** [comment]
Tried on version 3.10.10 and the latest one, 
When changing my user token or channel id the program will not boot up,
So that should not be the problem.

**Comment by thejoabo** [comment]
> Tried on version 3.10.10 and the latest one, When changing my user token or channel id the program will not boot up, So that should not be the problem.

There is no such version as "3.10.10", the last release is "experimental-2.0.0.2". **Do the bot (Virtual Fisher) has access to the channel/server you are specifying ?** Otherwise, AFB can't access the command list.

**Comment by MajorLOL** [comment]
> > Tried on version 3.10.10 and the latest one, When changing my user token or channel id the program will not boot up, So that should not be the problem.
> 
> There is no such version as "3.10.10", the last release is "experimental-2.0.0.2". **Do the bot (Virtual Fisher) has access to the channel/server you are specifying ?** Otherwise, AFB can't access the command list.

I was mentioning the python version, I noticed the program thay were using is called https://www.nanobot.gg/
and not virtual fisher my bad. I will close this topic since it is not part of this program
